name: flutter_date_pickers
description: Flutter package for day, week, range and month date pickers.
version: 0.3.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <1.0.0"
  buddhist_datetime_dateformat_sns: ^1.0.7

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
